//
//  ofxLSystem.h
//  nightgarden
//
//  Created by Stephen Detwiler on 3/8/16.
//
//

#ifndef ofxLSystem_h
#define ofxLSystem_h

#include "ofMain.h"
#include "lsystem.h"

typedef std::vector<ofMesh*> MeshVec;
typedef std::vector<ofNode*> NodeVec;

class ofxLSystem
{
public:
	ofxLSystem();
	ofxLSystem(char const* filename);
	~ofxLSystem();
	
	void load(char const* filename);
	void update();
	void draw();
	
	int getMaxSteps() const;
	void setMaxSteps(int v);

	int getCurrSteps() const;
	float getLastStepTime() const;

	float getStepInterval() const;
	void setStepInterval(float v);

	float getLastStepDuration() const;

	bool getDrawWireframe() const;
	void setDrawWireframe(bool v);
	
	LSystem const& getLSystem() const;
	
private:
	int mMaxSteps;				// The maximum number of steps to take.
	int mCurrSteps;				// The current count of steps taken.
	float mLastStepTime;		// The time the last step occurred.
	float mStepInterval;		// Time to wait between steps in seconds.

	float mLastStepDuration;	// How long it took to compute the last step.

	bool mDrawWireframe;		// Should the system be drawn in wireframe or solid?
	
	MeshVec mMeshes;			// The collection of meshes generated by the system.
	NodeVec mNodes;
	
	LSystem mSystem;
	
	void clear();
	void buildMeshes();
};

#endif /* ofxLSystem_h */
